// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using taller_proyecto_aws.Data;

namespace taller_proyecto_aws.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220323161345_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("taller_proyecto_aws.Models.Participante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("apellido")
                        .HasColumnType("text");

                    b.Property<string>("ciudad")
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .HasColumnType("text");

                    b.Property<double>("distancia")
                        .HasColumnType("double precision");

                    b.Property<string>("edad")
                        .HasColumnType("text");

                    b.Property<string>("genero")
                        .HasColumnType("text");

                    b.Property<string>("lugar")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<double>("ritmo")
                        .HasColumnType("double precision");

                    b.Property<string>("rol")
                        .HasColumnType("text");

                    b.Property<double>("tiempo")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
